-- mod-classless-wildcard: starter archetypes, generated by
-- data/sql/generators/gen_archetypes.py. Edit the builds there, not here.
--
-- An archetype is a build template a Classless Hero follows from level 1 to
-- 80: abilities = first-rank spell ids in unlock order, talents = talentId:rank
-- in purchase order. The server buys each entry as it becomes available.

CREATE TABLE IF NOT EXISTS `cw_archetypes` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `description` VARCHAR(255) NOT NULL DEFAULT '',
  `abilities` TEXT,
  `talents` TEXT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Classless starter archetypes';

DELETE FROM `cw_archetypes` WHERE `id` IN (1, 2, 3, 4, 5, 6);
INSERT INTO `cw_archetypes` (`id`, `name`, `description`, `abilities`, `talents`) VALUES
(1, 'Blade Dancer',
 'Fast melee striker: rogue strikes backed by warrior mobility.',
 '1752,2098,1784,100,772,53,1776,1715,5277,5171,1766,703,8676,1943,1856,5308,1833,408,18499,1680,6552,12294,1719,31224,5938,57934,51723',
 '201:2,221:5,181:5,1827:2,204:2,186:3,1122:5,223:1,242:5,1703:2,1706:2,1705:3,205:1,1707:2,1825:5,1709:1,2074:2,2075:2,2076:1,127:2,130:3,126:2,128:3,131:2,137:1,662:2,121:3,2232:2'),
(2, 'Battle Mage',
 'Armored caster: fireballs up close, sword in hand.',
 '133,168,1459,100,116,772,2136,118,5143,122,7384,1449,2120,1953,11366,2948,2139,45438,20252,6117,1680,11426,31661,1719,30482,44614,55342',
 '27:2,1141:3,26:5,34:5,31:3,30:3,29:1,23:2,1639:3,33:3,32:1,35:5,1733:3,36:1,1732:2,1734:3,1735:1,1850:3,1851:1,1852:1,127:2,130:3,126:2,128:3,131:2,137:1,662:2,121:3,2232:2'),
(3, 'Ranger of the Light',
 'Hybrid archer-paladin: shoot from range, heal and bless in melee.',
 '2973,635,465,1978,21084,20271,19740,3044,5116,13165,2974,19742,7294,2643,19750,3045,5384,642,1510,20473,4987,24275,56641,19801,31884,53351',
 '1344:5,2197:3,1806:3,1349:5,1818:2,1345:1,1819:2,1348:3,1353:1,1347:3,1804:2,1362:3,2130:3,1361:1,1821:3,1807:5,2134:5,2135:1,1432:5,1463:5,1444:3,1449:5,1628:2'),
(4, 'Shadow Mender',
 'Priest hybrid: shield and mend allies, wither foes with shadow.',
 '585,2050,1243,589,17,139,586,8092,588,8122,2054,527,2061,596,976,605,552,1706,2060,21562,34914,32379,32546,48045,64843',
 '465:3,462:5,482:2,463:3,481:5,501:1,461:3,881:2,484:1,1777:3,1781:2,521:1,1778:5,1816:3,1906:2,1779:1,1909:3,1907:5,1910:1,1898:5,346:3,344:2,352:1,347:3,348:1,343:3,341:2'),
(5, 'Stealthy Healer',
 'Druidic infiltrator: slip through shadows, restore life from hiding.',
 '5185,1784,5176,1126,774,8921,467,339,16689,8936,783,475,768,5215,1856,2893,740,29166,22812,21849,33763,31224,33786,50464',
 '821:2,823:3,824:5,841:3,829:3,827:1,843:5,830:3,831:1,828:5,1788:2,825:5,1797:3,844:1,1789:5,1791:1,1930:2,1917:1,2244:1,241:3,261:2,244:3,262:2,247:2,1123:3,245:3,246:1'),
(6, 'Storm Warrior',
 'Shamanistic bruiser: lightning from afar, heroic strikes up close.',
 '403,331,78,8017,8042,100,2484,324,8050,370,2645,57994,8056,845,5308,5675,8232,421,1680,1064,974,1719,51490,3738,51505,57755',
 '614:5,610:3,613:5,607:3,611:3,617:1,602:5,1647:2,616:1,2083:3,1689:3,1643:3,1690:1,1692:3,901:1,2249:1,2054:2,2057:5,2058:1,157:5,2250:3,159:5,166:3,154:4');
